baseURL = "https://mynaui.com/"
title = "Myna UI"
languageCode = "en-us"

enableGitInfo = true
enableRobotsTXT = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  description = "Perfect UI Components and Templates. Made with TailwindCSS. Open Source. Fully Responsive and Accessible. Free."
  author = "Praveen Juge"
  github = "https://github.com/praveenjuge/myna"
  og_image = "/og.png"
  twitter = "@praveenjuge"
